# Generated by Django 3.2.6 on 2021-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=100)),
                ('type_of_poison', models.TextField()),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
    ]
